#!/usr/bin/env node
"use strict";
var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
  // If the importer is in node compatibility mode or this is not an ESM
  // file that has been converted to a CommonJS file using a Babel-
  // compatible transform (i.e. "__esModule" has not been set), then set
  // "default" to the CommonJS "module.exports" for node compatibility.
  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
  mod
));
var __async = (__this, __arguments, generator) => {
  return new Promise((resolve, reject) => {
    var fulfilled = (value) => {
      try {
        step(generator.next(value));
      } catch (e) {
        reject(e);
      }
    };
    var rejected = (value) => {
      try {
        step(generator.throw(value));
      } catch (e) {
        reject(e);
      }
    };
    var step = (x) => x.done ? resolve(x.value) : Promise.resolve(x.value).then(fulfilled, rejected);
    step((generator = generator.apply(__this, __arguments)).next());
  });
};

// src/index.ts
var import_yargs = __toESM(require("yargs/yargs"));

// src/longscrape.ts
var import_chalk5 = __toESM(require("chalk"));
var import_puppeteer = __toESM(require("puppeteer"));

// src/getHeaderText.ts
var import_chalk = __toESM(require("chalk"));
function getHeaderText(page) {
  return __async(this, null, function* () {
    console.log("Getting header text:");
    const h1 = yield page.$eval("h1", (el) => el.textContent);
    if (!h1) {
      console.error(import_chalk.default.redBright("Could not find h1 element on page."));
      return process.exit(1);
    }
    return h1.trim();
  });
}

// src/getOrg.ts
var import_chalk2 = __toESM(require("chalk"));
function getOrg(page) {
  return __async(this, null, function* () {
    console.log("Getting originization...");
    const org = yield page.$eval(".breadcrumb li:nth-child(2) a", (el) => el.textContent);
    if (!org) {
      console.error(import_chalk2.default.redBright("Could not find second link in breadcrumb."));
      return process.exit(1);
    }
    return org.trim();
  });
}

// src/getDescription.ts
function getDescription(page) {
  return __async(this, null, function* () {
    console.log("Getting description...");
    const desc = yield page.$eval(".notes.embedded-content", (el) => el.textContent);
    if (!desc) {
      console.error("Could not find `.notes.embedded-content`.");
      return process.exit(1);
    }
    return desc.trim();
  });
}

// src/getUpdateRate.ts
var import_chalk3 = __toESM(require("chalk"));
function getUpdateRate(page) {
  return __async(this, null, function* () {
    console.log("Getting update rate...");
    const text = yield page.$eval(
      "tbody tr:nth-child(3) td.dataset-details",
      (el) => el.textContent
    );
    if (!text) {
      console.error(
        import_chalk3.default.redBright("Could not find `Update Rate` column in table.")
      );
      return process.exit(1);
    }
    return text;
  });
}

// src/getUpdateMethod.ts
var import_chalk4 = __toESM(require("chalk"));
function getUpdateMethod(page) {
  return __async(this, null, function* () {
    console.log("Getting update method...");
    const text = yield page.$eval(
      "tbody tr:nth-child(4) td.dataset-details",
      (el) => el.textContent
    );
    if (!text) {
      console.error(import_chalk4.default.redBright("Could not find `Update Method` in table."));
      return process.exit(1);
    }
    return text;
  });
}

// src/longscrape.ts
function longFetch(url, screenshot) {
  return __async(this, null, function* () {
    console.log(`Loading new ${import_chalk5.default.green("puppeteer")} instance...`);
    const browser = yield import_puppeteer.default.launch({ headless: "new" });
    console.log(`Opening new page...`);
    const page = yield browser.newPage();
    console.log(`Setting ${import_chalk5.default.yellow("User-Agent")} header...`);
    yield page.setUserAgent("datagov-external-client");
    console.log(`Visiting ${import_chalk5.default.blue(url)}...`);
    yield page.goto(url, { waitUntil: "networkidle0" });
    if (screenshot) {
      console.log(`Taking a screenshot...`);
      yield page.screenshot({ path: "temp.png" });
    }
    const name = yield getHeaderText(page);
    console.log(`Name: ${import_chalk5.default.green(name)}`);
    const org = yield getOrg(page);
    console.log(`Org: ${import_chalk5.default.green(org)}`);
    const desc = yield getDescription(page);
    console.log(`Description: ${import_chalk5.default.green(desc)}`);
    const updateRate = yield getUpdateRate(page);
    console.log(`Update Rate: ${import_chalk5.default.green(updateRate)}`);
    const updateMethod = yield getUpdateMethod(page);
    console.log(`Update Method: ${import_chalk5.default.green(updateMethod)}`);
    return process.exit(0);
  });
}

// src/index.ts
var argv = (0, import_yargs.default)(process.argv.slice(2)).option("u", {
  alias: "url",
  demandOption: true,
  type: "string",
  desc: "URL to scrape the data from."
}).option("s", {
  alias: "screenshot",
  type: "boolean",
  desc: "Whether to take a screenshot of the page.",
  default: false
}).parseSync();
longFetch(argv.u, argv.s);
